/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author ezrak
 */
public class MenuEntrada extends javax.swing.JFrame {

    /**
     * Creates new form MenuEntrada
     */
    public MenuEntrada() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVehiculo = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblFechaYHora = new javax.swing.JLabel();
        lblNotas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmpleado = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstVehiculo = new javax.swing.JList<>();
        txtNotas = new javax.swing.JTextField();
        txtFechaYHora = new javax.swing.JTextField();
        lblRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso de vehículos al Parking");
        getContentPane().setLayout(null);

        lblVehiculo.setText("Vehículo");
        getContentPane().add(lblVehiculo);
        lblVehiculo.setBounds(26, 14, 140, 16);

        lblEmpleado.setText("Empleado que recibe");
        getContentPane().add(lblEmpleado);
        lblEmpleado.setBounds(318, 14, 170, 16);

        lblFechaYHora.setText("Fecha y hora (dd/mm/aaaa HH:mm)");
        getContentPane().add(lblFechaYHora);
        lblFechaYHora.setBounds(26, 244, 210, 16);

        lblNotas.setText("Notas");
        getContentPane().add(lblNotas);
        lblNotas.setBounds(26, 295, 50, 16);

        lstEmpleado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstEmpleado);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(318, 42, 282, 146);

        lstVehiculo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstVehiculo);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(26, 42, 194, 146);
        getContentPane().add(txtNotas);
        txtNotas.setBounds(75, 292, 550, 22);
        getContentPane().add(txtFechaYHora);
        txtFechaYHora.setBounds(240, 240, 383, 22);

        lblRegistrar.setText("Registrar");
        getContentPane().add(lblRegistrar);
        lblRegistrar.setBounds(264, 350, 90, 23);

        setBounds(0, 0, 652, 453);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFechaYHora;
    private javax.swing.JLabel lblNotas;
    private javax.swing.JButton lblRegistrar;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JList<String> lstEmpleado;
    private javax.swing.JList<String> lstVehiculo;
    private javax.swing.JTextField txtFechaYHora;
    private javax.swing.JTextField txtNotas;
    // End of variables declaration//GEN-END:variables
}
