/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author ezrak
 */
public class MenuServicioAdicional extends javax.swing.JFrame {

    /**
     * Creates new form MenuServicioAdicional
     */
    public MenuServicioAdicional() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmpleado = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstVehiculo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEmpleado = new javax.swing.JList<>();
        lblVehiculo = new javax.swing.JLabel();
        lblServicio = new javax.swing.JLabel();
        lblFechaYHora = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtFechaYHora = new javax.swing.JTextField();
        cmbServicio = new javax.swing.JComboBox<>();
        txtCombo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Servicios Adicionales");
        getContentPane().setLayout(null);

        lblEmpleado.setText("Empleados");
        getContentPane().add(lblEmpleado);
        lblEmpleado.setBounds(260, 20, 180, 16);

        lblCosto.setText("Costo");
        getContentPane().add(lblCosto);
        lblCosto.setBounds(260, 230, 60, 16);

        lstVehiculo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstVehiculo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 210, 146);

        lstEmpleado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstEmpleado);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(260, 60, 210, 146);

        lblVehiculo.setText("Vehículos");
        getContentPane().add(lblVehiculo);
        lblVehiculo.setBounds(20, 20, 210, 16);

        lblServicio.setText("Servicio");
        getContentPane().add(lblServicio);
        lblServicio.setBounds(20, 230, 80, 16);

        lblFechaYHora.setText("Fecha y hora (DD/MM/AAAA HH:MM");
        getContentPane().add(lblFechaYHora);
        lblFechaYHora.setBounds(20, 270, 220, 16);

        btnRegistrar.setText("Registrar");
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(200, 350, 100, 23);
        getContentPane().add(txtFechaYHora);
        txtFechaYHora.setBounds(260, 270, 210, 22);

        cmbServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbServicio);
        cmbServicio.setBounds(80, 230, 72, 22);
        getContentPane().add(txtCombo);
        txtCombo.setBounds(320, 230, 71, 22);

        setBounds(0, 0, 577, 481);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuServicioAdicional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuServicioAdicional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuServicioAdicional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuServicioAdicional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuServicioAdicional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbServicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFechaYHora;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JList<String> lstEmpleado;
    private javax.swing.JList<String> lstVehiculo;
    private javax.swing.JTextField txtCombo;
    private javax.swing.JTextField txtFechaYHora;
    // End of variables declaration//GEN-END:variables
}
