/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author ezrak
 */
public class MenuSalida extends javax.swing.JFrame {

    /**
     * Creates new form MenuSalida
     */
    public MenuSalida() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblComentarios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEmpleado = new javax.swing.JList<>();
        lblListaEntradas = new javax.swing.JLabel();
        lblListaEmpleado = new javax.swing.JLabel();
        lblHoraSalida = new javax.swing.JLabel();
        txtFechaYHora = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        kstVehiculos = new javax.swing.JList<>();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Salidas");
        getContentPane().setLayout(null);

        lblComentarios.setText("Comentarios");
        getContentPane().add(lblComentarios);
        lblComentarios.setBounds(20, 290, 120, 30);

        lstEmpleado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstEmpleado);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(270, 60, 230, 150);

        lblListaEntradas.setText("Vehiculos actuales");
        getContentPane().add(lblListaEntradas);
        lblListaEntradas.setBounds(20, 20, 130, 30);

        lblListaEmpleado.setText("Empleado que retira");
        getContentPane().add(lblListaEmpleado);
        lblListaEmpleado.setBounds(270, 20, 120, 30);

        lblHoraSalida.setText("Fecha y Hora de salida");
        getContentPane().add(lblHoraSalida);
        lblHoraSalida.setBounds(20, 240, 140, 30);

        txtFechaYHora.setText("DD/MM/AAAA HH:MM");
        txtFechaYHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaYHoraActionPerformed(evt);
            }
        });
        getContentPane().add(txtFechaYHora);
        txtFechaYHora.setBounds(160, 250, 340, 22);

        txtComentarios.setColumns(20);
        txtComentarios.setRows(5);
        txtComentarios.setText("Aguante la vela Puerca");
        jScrollPane4.setViewportView(txtComentarios);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(160, 290, 340, 60);

        kstVehiculos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(kstVehiculos);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(20, 60, 230, 150);

        btnRegistrar.setText("Registrar");
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(210, 410, 110, 23);

        setBounds(0, 0, 554, 493);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaYHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaYHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaYHoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSalida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> kstVehiculos;
    private javax.swing.JLabel lblComentarios;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblListaEmpleado;
    private javax.swing.JLabel lblListaEntradas;
    private javax.swing.JList<String> lstEmpleado;
    private javax.swing.JTextArea txtComentarios;
    private javax.swing.JTextField txtFechaYHora;
    // End of variables declaration//GEN-END:variables
}
